name: CICDPipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

- name: Deploy
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GH_TOKEN }}
    publish_dir: ./public